### ISSUE TITLE
Remember last radio, playlist,...

### ISSUE THREAD

**Issue by ilopmar** [Quacky2200/Spotify-Web-Player-for-Linux#11]
If I'm listening a radio or playlist and close the application, when I started it again it doesn't remember the radio, playlist,... So I need to find what I was listening.

It would be nice if it could remember what I was listening and start at the same song.

**Comment by Quacky2200** [comment]
I was thinking of creating this functionality, currently with the separate node process it makes it hard to reload windows once they are loaded due to the way it is managed, I will work on seeing if I could make some kind of save system. I was thinking of linking this into some kind of URI linking system so that you can open Spotify uri'/links in the player locally - I'm not too sure on how that works on Linux at the moment though...

**Comment by Quacky2200** [comment]
I have added a basic lastURL to the preferences in the latest commit - it doesn't currently work (it gets overwritten when it's loading) so I will make sure this gets overridden and working for the next commit (probably in the next few days)

**Comment by Quacky2200** [comment]
Added in https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/1.0.0
