### ISSUE TITLE
support for keyboard media controls

### ISSUE THREAD

**Issue by Mondane** [Quacky2200/Spotify-Web-Player-for-Linux#20]
Now that D-Bus support is added, how about adding support for the hardware keys to start/paus/next/previous ? If it's added, it's not working in the 64bit version ( https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/0.9.5-1 )

**Comment by Quacky2200** [comment]
I thought that Ubuntu's sound menu would do that but never the less I can implement it. For now, you can implement the play/pause next and previous buttons as a custom dbus-send command - I know this isn't what you had in mind but it's one way to do it until it's sorted
![screenshot from 2016-09-08 13-45-44](https://cloud.githubusercontent.com/assets/4623599/18349772/ade97aac-75ca-11e6-94c7-1e90b829016c.png)

**Comment by ilopmar** [comment]
@Mondane with the code introduced here #7 the keyboard shortcuts are working the play/pause/next/previous. In using Linux Mint, which is based on Ubuntu, so I think that should work for you.

**Comment by Quacky2200** [comment]
Fixed properly in https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/1.0.0

**Comment by Plasmodium1** [comment]
Unfortunately on Xubuntu 16.04 LTS, the media keys only work if the Spotify window is in focus. Not entirely sure if this bug is to do with my OS or your application.

Otherwise I am greatly appreciating the changes in the latest version and recommending it to my Linux using friends!

(Apologies if this is the wrong place to report such an issue, I am fairly new to github!)

**Comment by ilopmar** [comment]
@Plasmodium1 I'm using Linux Mint with Cinnamon which is based on Ubuntu 16.04 LTS and the shortcuts are working no matter which application has the focus.

Instead of creating a custom shortcut, could you try to add a new one to the actual shortcuts:

![image](https://cloud.githubusercontent.com/assets/559192/19775474/c82e1c16-9c70-11e6-9356-6808c06189bd.png)

If I push `Alt+Super+p` the music stops and if I push it again it continues.

**Comment by Plasmodium1** [comment]
I have not created any custom shortcuts (at least, not pertaining to media keys) - this is simply with me pressing the dedicated play/previous/skip buttons on my keyboard (so if this thread is specifically about custom shortcuts, then perhaps I have posted in the wrong thread? My apologies if so). These media keys control playback on Rhythmbox just as would be expected (ie, no matter what window has focus).

Unfortunately, Xfce's keyboard shortcut menu is not so comprehensive as Cinnamon's and does not include media keys, nor multiple shortcuts per command. However, if I add the commands listed above (in the second post) as shortcuts, it does work for Spotify, but hijacks the keys so that they no longer work in Rhythmbox.

**Comment by Quacky2200** [comment]
When v1.0.0 was released I implemented D-Bus media key support and they work fine on Ubuntu. I have a feeling it could perhaps be a wrong string set in the dconf setting `org.gnome.settings-daemon.plugins.media-keys`. The string for Play, Pause, Next, etc should include the prefix XF86.

To set the right key for raising the volume for example:
`
gsettings get org.gnome.settings-daemon.plugins.media-keys volume-up
'XF86AudioRaiseVolume'
`

The media keys and their assigned media key binding code
```
keycode 162 = XF86AudioPlay
keycode 164 = XF86AudioStop
keycode 144 = XF86AudioPrev
keycode 153 = XF86AudioNext
```

I did remove global shortcuts that electron used at the time as I forgot to include them when I reformatted the controller script

**Comment by Plasmodium1** [comment]
As far as I can see (through dconf editor), there is no "org.gnome.settings-daemon.plugins.media-keys" setting on my system. If I run `gsettings get org.gnome.settings-daemon.plugins.media-keys volume-up` (which as I understand should show me the current function of that shortcut), gsettings says `no such schema`

Is it possible Xfce handles this differently? Or will running the command you gave above with `set` create the schema therefor fixing the issue?

**Comment by toaomatis** [comment]
I also run Xubuntu 16.04 and have V1.0.0 installed. I can confirm that only the media keys work when the Spotify Web Player is in focus. 
Executing the same commands as @Plasmodium1 give the same result on my system. However the following commands do work, even when SWP is in the system tray or on an other workspace (I have 4).
``` 
dbus-send --print-reply --reply-timeout=2500 --session --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
``` 
After few seconds (most likely the timeout) I get the following error:
```
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote 
application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
``` 
But the music do pause and play. Same goes for next and previous. I reduced the timeout to 100ms and it works like a charm now. 

Volume on my system goes via the global Volume Control (PulseAudio).

**Comment by Quacky2200** [comment]
@toaomatis @Plasmodium1 That's because dbus-send has the option for functions to send back a value which they never do because they call methods (methods do not send back values, they simply execute code) - I looked in the man pages to see if I could remove the message since it's a pain seeing it when there's no need for an error to occur. I have realised that you can remove `--print-reply --reply-timeout=2500` with  `--type=method_call`.

Here's an example:
```
dbus-send --type=method_call --session --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
```

**Comment by toaomatis** [comment]
Thanks for your reply. I applied your suggestion to all three Media Key shortcuts and they work like a charm.
No noticeable delay and without errors / exceptions :+1:
