### ISSUE TITLE
get_prerequisites.sh doesn't install everything needed

### ISSUE THREAD

**Issue by uosiu** [Quacky2200/Spotify-Web-Player-for-Linux#22]
I'm using Linux Mint 18 with Cinnamon.
I've ran ./get_prerequisites.sh and get: http://pastebin.com/RBmaui6j
OK, node and electron is downloaded and app should be ready for launch.
Unfortunately, some node modules are missing.

stdout+stderr from app is: http://pastebin.com/0bSBksCB

**Comment by Quacky2200** [comment]
There's an issue from before that has been followed so that a guy could install Spotify Web Player for Linux on Fedora with an RPM. I explained that due to the node_modules having to be built for each architecture, I have not released them publicly and there's a download link to get the node_modules zip there. The debian packages have node_modules for you but the source doesn't.

I will close this issue assuming that the simple download from the link provided will have solved your issue.
https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/issues/13#issuecomment-245160187
