### ISSUE TITLE
Encoding issue on radio's page

### ISSUE THREAD

**Issue by quentinus95** [Quacky2200/Spotify-Web-Player-for-Linux#26]
Hello,

There is a small encoding issue on Radio's page on the title, I don't know if you have the ability to fix it.

![capture du 2016-09-28 21-54-43](https://cloud.githubusercontent.com/assets/8060564/18929957/762ecb06-85c6-11e6-9e21-c99e454796bd.png)

Thanks for your work !

Quentin

**Comment by quentinus95** [comment]
Same issue on the bottom of the page

![capture du 2016-09-28 22-22-59](https://cloud.githubusercontent.com/assets/8060564/18930891/300119c8-85ca-11e6-9b4a-605497ecbb1c.png)

**Comment by Quacky2200** [comment]
I'll see about the notification encoding issue, this probably just needs to be manually changed to UTF-8. Do you have the Spotify track URI/URL so that I can repeat this test?

Also, I don't edit anything on the bottom of the page so the radio genres might be a Spotify issue itself. If you see the issue on both Spotify Web Player for Linux and the live Spotify Web Player in another browser, it may just be a Spotify issue.

**Comment by Quacky2200** [comment]
Looks like it may be similar to this Spotify issue: "[incorrect encoding is used in related music titles](https://community.spotify.com/t5/Ongoing-Issues/Web-Player-Incorrect-Encoding-is-used-in-Related-Music-titles/idi-p/1401784)"

I can try looking at re-encoding the page as Spotify has not fixed this since the issue was released in July.

**Comment by quentinus95** [comment]
Yes, I confirm it is an issue on their side. I don't know if you will be able to re-encode the page as it is happening only on certain sub parts of the pages.

**Comment by Quacky2200** [comment]
I'm going to close this as it's Spotify's problem.

If this is really important for you to get fixed, I would contact Spotify using their community forum in the web player section. I would tell them the encoding issue and what pages it occurs on and hope that they can fix it so that it is fixed for everyone and all pages affected. 

I would fix this but as it's only a few pages and it's their encoding, I would rather they fixed it so that it's fixed globally rather than just an application, as it could become an unnecessary performance issue when having to re-encode/decode pages.
