### ISSUE TITLE
No sound in 1.0.0

### ISSUE THREAD

**Issue by wa4557** [Quacky2200/Spotify-Web-Player-for-Linux#46]
I have absolutely no idea why it is not working but I have no sound coming from the app when using version 1.0.0. Music seems to play fine (i.e. seeker is moving) but nothing comes out from the speakers.

Running the app from terminal yields:

```
NOT SANDBOXED
Vector smash protection is enabled.
```

**Comment by Quacky2200** [comment]
General and obvious things to check:

- Have you recently reset your WiFi/Ethernet connection whilst running the application? 
  - Have you tried to restart the application?

- Have you checked if the application is muted in the 'Applications Tab' in the Sound Preferences window?

- Are you sure you've set the right device as the output device in the Sound Preferences window? 

- Do you have Flash installed for any browser?

The application no longer yields debugging information to the terminal because most of the errors/warnings that get logged are normally irrelevant. At the moment they can only be seen in the DevTools window, you can turn on the DevTools in the preferences window if you want to see if there's anything worth noticing. 

There's not really that much I can do with your situation. What distribution and architecture are you running this on?

**Comment by Quacky2200** [comment]
Closing due to lack of communication for 10 days

**Comment by richardspruill** [comment]
@Quacky2200 I am experiencing this on Ubuntu 16.04. I get normal sound on the official spotify web player

**Comment by Quacky2200** [comment]
I think this may be a problem with flash and the sound mixer/setup you have. Do you have pulseaudio and ALSA installed? Are you using Jack or some other type of audio setup (including perhaps some hardware?) that is different from a typical Ubuntu install? I can't think of any other reason why it would fail as a failure with Flash would've prevented you to play music within the app.

**Comment by wa4557** [comment]
I figured it out for me running Ubuntu. I Installed pavucontrol and there the player was assigned to use the HDMI output for audio. Changing that to the headphone jack (which I was using) solved the issue.

**Comment by Quacky2200** [comment]
Ahh that's good to hear, hopefully it's the same issue for @richardspruill :+1:
