### ISSUE TITLE
App causes suspend-resume issues

### ISSUE THREAD

**Issue by esecules** [Quacky2200/Spotify-Web-Player-for-Linux#54]
After installing the app, my laptop (Asus Zenbook CA305 on Ubuntu 16.04) it has failed to resume from suspend, instead it crashes and does a full boot. I get a crash report for the executable "/usr/share/apport/apportcheckresume".

The problem is resolved when I uninstall the app and reappears after I reinstall. Im not sure whether this is a regression because I am a first time user. I downloaded the ```spotifywebplayer_v1.0.0_x64.deb``` package from the releases page. 

I realize there may not be enough info to go off of here but I will update as I find out more.

**Comment by Quacky2200** [comment]
The executable that you referenced is not part of my application or package. It's actually part of the apport package (a debugging/bug crash tool). Apport can be the most buggiest piece of software despite trying to be good at debugging (IMHO). What you witnessed looks as if apport crashed all by itself and it's complaining. If it were my application it would have a different executable and I can only assume 'apportcheckresume' runs when the computer is resumed from standby. 

Of course this only happens when my package is installed but unless there's some more information as to whether my application is actually causing apport to crash, I have a feeling that your computer perhaps has another problem in some other aspect?

**Comment by Quacky2200** [comment]
Any update on this issue? Perhaps an AppImage will help you determine if it's down to an install?
