### ISSUE TITLE
Im getting Bad substitution

### ISSUE THREAD

**Issue by Fr3llD** [Quacky2200/Spotify-Web-Player-for-Linux#55]
I'm on Ubuntu 16.10 and im getting this after the install. I did no troubleshooting, so it might be an easy thing to fix. 

/usr/bin/spotifywebplayer/spotifywebplayer: 2: /usr/bin/spotifywebplayer/spotifywebplayer: Bad substitution
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to get path
    at Error (native)
    at Object.<anonymous> (/usr/bin/spotifywebplayer/libs/electron/resources/electron.asar/browser/init.js:156:39)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:360:7)
    at startup (bootstrap_node.js:152:9)

**Comment by Quacky2200** [comment]
Can you please make sure that you have the libs folder present at `/usr/bin/spotifywebplayer/libs/` along with the node `/usr/bin/spotifywebplayer/libs/node/` and electron `/usr/bin/spotifywebplayer/libs/electron/` folders.

Can you also make sure your home folder and the `~/.spotifywebplayer/` folder (and everything inside) is read and writeable? 

I'm currently unsure what exactly the problem is as it's an error from electron but let's start from here.

**Comment by toaomatis** [comment]
Why not update the shebang to `#!/bin/bash` while the script only works with bash?

I use (oh-my-)zsh as interpreter and `/bin/sh` is linked to `dash`. I updated the shebang for spotifywebplayer to bash and it worked.

**Comment by Quacky2200** [comment]
Ah, my apologies, I didn't realise about the shebang and I don't know why I ever kept it as /bin/sh. I'm glad you found the mistake :)

**Comment by Fr3llD** [comment]
yes, works! thanks!
