### ISSUE TITLE
similar project

### ISSUE THREAD

**Issue by xxcriticxx** [Quacky2200/Spotify-Web-Player-for-Linux#56]
@Quacky2200 please look at this project

https://github.com/pascalopitz/unoffical-sonos-controller-for-linux

**Comment by Quacky2200** [comment]
I don't see how this is an issue?

I did make sure to take a peek but I don't understand how this project is in anyway related? Sonos is just a service that allows music to be played over Wi-Fi and change tracks, volume, etc - you still need an official sonos compatible application to play music over a sonos speaker. However, my repo is just a direct Spotify Web based electron implementation - I do know a similar project called SpotiWeb by tomasmcm but I haven't seen much activity over the past couple of months.

**Comment by xxcriticxx** [comment]
both project are based on electron and spotify is one of many services that sonos provides. anyways maybe you can look at the code and help out.

**Comment by Quacky2200** [comment]
I've seen in the issues that others want Amazon Music and other services available but truth be told is that I wouldn't really have much of a clue. 

For example, I assume that this sonos application just redirects the stream to itself so it can control playback? Spotify's connection gives a ton of information back and forth (user information, logging, track metadata, etc) but the music has been re-encoded since approx. last May to stop people being able to access the stream. Unless you can just redirect an actual stream somewhere within all these services, I bet the services would soon change to adapt.

If I ever find anything to contribute I will, for now I'm pretty busy IRL which is why my application has not seen much attention recently. :+1:

**Comment by xxcriticxx** [comment]
thx for the answer i give your project try today
