### ISSUE TITLE
Low resolution thumbnail

### ISSUE THREAD

**Issue by samuelcecilio** [Quacky2200/Spotify-Web-Player-for-Linux#64]
Hi, Thumbnail is in low resolution.

I'm using KDE Neon but same happens Ubuntu 16.10.

![screenshot_20170116_130719](https://cloud.githubusercontent.com/assets/4163818/21988048/0334aeb8-dbed-11e6-9fed-4c76fe3add00.png)

Thanks.

**Comment by Quacky2200** [comment]
I was going to recommend a fix but it's actually impossible to do since the source code is built into electron when it's built. Unless you want to create a development environment to change source code then you may have to wait until the next version and I can always include a resolution setting. The reason the album art is small was to reduce overall cache disk space. 

If you wish to change code, in `./windows/spotify/controller.js` you can change the 0 from `this.track.art = details.track.images[0][1];` to the length which will give you the biggest resolution (e.g. `this.track.art = details.track.images[details.track.images.length][1];`) as seen in [v1.0.30 controller.js Line 69](https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/blob/master/windows/spotify/controller.js#L69

**Comment by Quacky2200** [comment]
@develar how does electron-builder implement .desktop icons so that I could implement system icons first before my own as a backup?
