### ISSUE TITLE
Tray icon dissapears after sign out

### ISSUE THREAD

**Issue by juulderuysscher** [Quacky2200/Spotify-Web-Player-for-Linux#66]
When I sign out and sign in again the image of the tray icon isn't displayed anymore. (It becomes a prohibition sign)

![schermafdruk van 2017-01-21 16-25-34](https://cloud.githubusercontent.com/assets/9530637/22175534/d3bf6cfa-dff6-11e6-80ca-8b61fcd2b196.png)

There is no special command line output with an error.
Node version: 6.9.1
Ubuntu: 16.10

**Comment by coxackie** [comment]
I have too noticed the prohibition sign appearing after a while. For me, it happens even without signing out. Ubuntu 16.10.

**Comment by Quacky2200** [comment]
What version of the app are you running? Is this a normal installation (e.g. debian install or custom install)?

**Comment by coxackie** [comment]
Version is 1.0.25, although it was also doing it for 1.0.0. Debian install (from the .deb file)

**Comment by juulderuysscher** [comment]
I installed it via spotifywebplayer_1.0.35_amd64.deb and I had the same issue with the previous version.

**Comment by Quacky2200** [comment]
OK thanks for the info. I think this is just a garbage collection issue since it also happens whilst signed in at some inconvenient time. It may be part of the refresh bug I've been trying to fix where garbage collection would remove important variables despite being set as constants or global values. It should be gone in the next version assuming it's part of it :+1:
