### ISSUE TITLE
Can't log in to Spotify?

### ISSUE THREAD

**Issue by bswarm9568** [Quacky2200/Spotify-Web-Player-for-Linux#67]
On Ubuntu Gnome 16.04, installed spotifywebplayer_1.0.35_amd64.deb along with depends. On startup it shows the "log in with Spotify" button, which when clicked opens and immediately closes another window, then still shows the "log in with Spotify" button again. When run in terminal the following shows up...
```
spotifywebplayer
changed { Identity: 'spotifywebplayer' }
changed { SupportedUriSchemes: [ 'http' ] }
changed { SupportedMimeTypes: [ 'application/www-url' ] }
Failed to encode dictionary
Failed to encode reply value
Failed to encode dictionary
Failed to encode reply value
```

**Comment by Quacky2200** [comment]
Have you tried to restart the app and login again? Facebook cookies are not very well implemented with Electron. 

To be honest, unless someone is willing to develop and debug with their own Facebook account I can't test this

**Comment by bswarm9568** [comment]
I logged in with my Spotify username/password, which are correct.

**Comment by Quacky2200** [comment]
Do you think you may have this issue #53 instead? Since the 'Log in with Spotify' button sounds different to my login page...?
![screenshot from 2017-01-23 01-24-56](https://cloud.githubusercontent.com/assets/4623599/22188226/eddb266e-e10a-11e6-9320-b78a9b2f4108.png)
![screenshot from 2017-01-23 01-25-09](https://cloud.githubusercontent.com/assets/4623599/22188227/eddc5f8e-e10a-11e6-9635-944211187d9e.png)

**Comment by bswarm9568** [comment]
That screenshot is what showed up the first time running it. After I logged in with my Spotify account all I see now is a green button that says "log in with Spotify", nothing else.

**Comment by Quacky2200** [comment]
I have a feeling that this is related to #53 then since that would never normally happen and it sounds as if Spotify is trying to redirect you to open.spotify.com. If you were to open up the dev console with Ctrl-Shift-i and then put this into the console - what happens?

```
windowHook = false;
window.location = 'https://open.spotify.com'
```

**Comment by bswarm9568** [comment]
It reloads the same thing and in the console says
 "preload.js:151 Uncaught ReferenceError: controller is not definedwindow.onbeforeunload @ preload.js:151
Navigated to https://open.spotify.com/browse

**Comment by Quacky2200** [comment]
Yeah the preload error is due to the app intending to work for play.spotify.com and is part of the refresh bug I've been fixing. Is your account tied to a Facebook account? Do you have/did you have a premium membership? Sadly this bug cannot be fixed and is 99% part of the issue I referenced - sorry for the news. I also suspect Spotify are trying to move people away from their web player similar to this [post posted on the Spotify Community forum](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Can-t-stop-play-spotify-com-from-redirecting-to-open-spotify-com/m-p/1560272). If the main spotify player window was hidden, it was most-likely a redirect that caused it to initiate a hide - otherwise the window hiding was a Facebook login window (which spams new popup windows until a login occurs due to the terrible cookie bug I have encountered).

**Comment by bswarm9568** [comment]
I cleared the cache in the .spotifywebplayer folder and tried logging in with facebook instead of Spotify, a different problem now. Another window keeps opening and closing continuously until I force close the program.

**Comment by Quacky2200** [comment]
Yeah that's the Facebook login window - it's supposed to stop after around 10 window open/closes when it finally 'accepts' the new cookies being set in the main window, if that doesn't work, you normally have to force-close the app, and restart the app *but* if it's going to say 'Login with Spotify' after a succesful login you still have the same issue. I personally wouldn't bother if you see the message again or you can't login since it's just a very annoying until I ever find a fix.

**Comment by bswarm9568** [comment]
I created a new account within the spotifywebplayer, now it works.

**Comment by mmsdivino** [comment]
I have same error since version 1.0.35 on Ubuntu 16.04 and I upgraded to 1.0.40 and it's happing too.
In another computer (version 1.0.40 on Ubuntu 16.10) I have the same issue. 
I login without my Facebook account on both computers.

**Comment by Quacky2200** [comment]
Sorry did you mean that it fails on a normal Spotify account login too or just Facebook login? Facebook login is very experimental that hasn't worked well since v1 due to the switching to a big refactor using a global value until switching it again in v1.0.25 onwards. If you can login with both accounts fine on v0.8.19 then I will put this as a confirmed bug as it doesn't affect me and I can't test

**Comment by mmsdivino** [comment]
It fails on a normal Spotify account login and this problem for me started in v1.0.35. I'll try again.

**Comment by Quacky2200** [comment]
Having premium is most likely the reason why your account was upgraded to the new Login/UI more quickly

**Comment by tylerecouture** [comment]
I couldn't log in with my username (prompt asks for username) but when I used my email instead I was able to log in.  Ubuntu 16.04, Basic/Free Spotify account, Player v1.0.40 Beta

**Comment by Quacky2200** [comment]
The login prompt was not created or modified by me, I would ask Spotify if the same happens on the website

**Comment by coxackie** [comment]
I am having in the last 3 days the exact same problem that bswarm9568 mentioned on 23 Jan, with the exact same screen shot. I have tested in on 3 computers (ubuntu 16.04 and 16.10, spotify web player version 1.0.35 and 1.0.40). I have an account with email - not Facebook. I have erased the cache directory, it shows me the log-in page, I log in, but then immediately it goes to the screen shot that  bswarm9568 shown, and no matter how many times I press the "Log in with Spotify" button nothing happens (a window pops up and immediately gets closed).

**Comment by Quacky2200** [comment]
Sadly this is just part of Spotify and their new interface which I have not implemented yet. We've found that people who had or use premium get affected by this bug. Until I get the new interface I cannot build another version without having to reintroduce all the features (if it's possible) and at that point I don't know if I will be making another version as it is already a cat-mouse situation - Spotify also uses CEF as part of their implementation, so both aren't exactly light on resources.

**Comment by MartinsThiago** [comment]
Same problem here... I tried using both **.deb** and **.AppImage**

System: ElementaryOS 0.4 Loki

**Comment by coxackie** [comment]
May I also add that I am not, and never was, a premium user of spotify. I have an account through google with spotify, but that is all. Just mentioning this to point out that the issue does not affect only users with premium account (or under facebook login).

**Comment by siqueiraets** [comment]
I also had this problem with a premium account. Then, I read that the spotify new UI is not released for firefox yet and was able to fix the issue by forcing the electron user agent to a firefox one. I've changed the code so the loadURL call uses the new user agent:

`
this.loadURL((app.settings.lastURL && app.settings.lastURL.indexOf('play.spotify.com') > -1 ? app.settings.lastURL : App.HOST), {userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1'});
`

This workaround is working for me.

**Comment by Quacky2200** [comment]
That's a good solution, it would be interesting to see if it works for everyone. The most likely reason is that Mozilla probably doesn't have the ability to host DRM content via HTML5 components unlike Chrome forcing it to use Flash. The problem is a matter of time - either where Mozilla gain the ability to play DRM content or once Spotify work beyond this issue (if it is DRM content I'm not sure but either way) - we're back to the drawing board. I'm also unsure how easy it will be to adapt my code to the new interface - it could be locked down even further.

**Comment by Quacky2200** [comment]
A new fix for anyone who may want to continue to use my application has been applied in commit b325d4c391f9d1e8749b71c16290433837625173. A new release will be available ASAP.
