### ISSUE TITLE
Sing! feature doesn't work

### ISSUE THREAD

**Issue by akritiko** [Quacky2200/Spotify-Web-Player-for-Linux#72]
I installed Spotify Web Player for Linux (Ubuntu 16.04 LTS). Didn't receive an error. Tried the Sing! feature in a song and received the following error:

![selection_01](https://cloud.githubusercontent.com/assets/445175/22627177/680f4fc6-ebc6-11e6-8070-a88dc3a769b5.png)

Went to the specified directory and discovered that LyricCache folder wasn't auto generated. After I created the folder manually, everything worked fine.

**Comment by Quacky2200** [comment]
Yes I noticed this a day or two ago, I must have accidentally forgot to put the generating folder function in whilst adding the Sing! Sync functionality in. I think there's also a problem with new synchronisations where they don't get uploaded now due to moving some web scripts around. I'll come back to this sometime today/tomorrow

**Comment by Quacky2200** [comment]
Whilst the synchronisations upload ability has been fixed it might be a bit of time before I get the chance to re-upload another release
