### ISSUE TITLE
Solution For Using Client Outside Us/Uk

### ISSUE THREAD

**Issue by rashi-kp** [Quacky2200/Spotify-Web-Player-for-Linux#73]
Spotify is officially not available in my country i do love ur client apart from the official client & i miss listening to my playlist is there any way to get it working on my system ? i am running ubuntu mate 14.04

**Comment by Quacky2200** [comment]
Spotify is most likely unavailable either because Spotify may be unable to currently host music to your country due to licensing issues or it might be blocked by law. Despite people using VPN's and proxies; I would imagine it would be wise not to try and bypass this as it could be illegal in your country (See [is using a VPN to access blocked content illegal? - Techly Australia](http://www.techly.com.au/2014/01/30/using-vpn-access-blocked-content-illegal/)). Please make sure you're not doing anything illegal to gain access to Spotify or any other service - it's not worth the risk.

The best plan of action would be to ask Spotify directly [by email (customer service)](mailto:support@spotify.com) or the [community forum](https://community.spotify.com/t5/Help/ct-p/Help) to see their reasoning behind not hosting their service in your country.
