### ISSUE TITLE
MPRIS question

### ISSUE THREAD

**Issue by pcmitsis** [Quacky2200/Spotify-Web-Player-for-Linux#74]
Dear all,
I just tested your application on my ubuntu system and works like a charm! I have two questions though:
I am using MPRIS to control the application from the terminal for example: 
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
`. Although that the functionality is there I have to send a SIGINT to dbus-send as it stalls. Do you know why this is happening?
In addition is it possible upon the application startup to start playing music immediately from a specific list (using MPRIS or terminal arguments)?

Cheers,
Panos

**Comment by Quacky2200** [comment]
Please refer to [support for keyboard media controls](https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/issues/20#issuecomment-268817734) to fix the your SIGINT stall issue

MPRIS does have an openUri function which I had previously set up to play a certain track URI but the functionality has been accidentally removed as seen by [Controller Line 127](https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/blob/1.0.40/windows/spotify/controller.js#L127) where the function playTrack is not defined however this is what it should look like until I can implement it next
```
function playTrack (uri) {
     if (uri.indexOf('spotify:track:') < 0) return;
     SpotifyApi.api.request('player_play_track', [this.player_id, uri, 0, undefined]);
}
```

If you want to test this you can press Ctrl-Shift-I (letter i) to enter the Dev Console and input this into the console: 
```
SpotifyApi.api.request('player_play_track', ['main', 'spotify:track:2ASYhdpeSSKBpY83i10Xz0', 0, undefined])
```

**Comment by pcmitsis** [comment]
Dear @Quacky2200 ,
Thank you very much for your fast and complete reply! I have one last question, I want to try to build the source also for my Raspberry PI v3 with an arm processor. 
Could you point out the procedure (it is the same like v1.0.0 that is in the readme or something changed to the current version)? Spotify web works fine with chromium on RPI and if an export to it is possible, then it can become easily adapted by a lot of people (there is no spotify-client for RPI!)

Cheers,
Panos

**Comment by Quacky2200** [comment]
I am afraid that I don't have much experience trying to the application to work on a Raspberry Pi. However assuming you could find an ARM compatible pepper flash for Chrome, download Node.js and have some experience programming then I think you'd be able to just about pull it off. 

Firstly it would be better to start off with a newer version of the application since it doesn't rely on Node and Electron binaries like v1.0.0. You could then use npm to install Electron, after that you would need to place the ARM libpepperflash.so in `./plugins/`. The application will find the plugin with a processor suffix (aka 'x64', 'ia32', 'arm64') such as `libpepperflash-arm64.so`. You will also need to able to compile native bindings for d-bus support (at the moment I cannot remember all the libraries that I have installed to be able to compile them but any missing library modules will be easily searchable so that you can install them later). After that you should be able to use the application on the Pi but it would probably be quite slow as Chromium is heavy for ARM devices.

**Comment by pcmitsis** [comment]
Thanks @Quacky2200 , the reason that I am interested in porting this player to RPI is to use some GPIO buttons to change the music via MPRIS and not using the graphical interface at all (start it minimized). 

I will let you know with a PR if I made it, for now I consider this issue closed!

Cheers,
Panos
