### ISSUE TITLE
Mute during ads on the free version

### ISSUE THREAD

**Issue by ilopmar** [Quacky2200/Spotify-Web-Player-for-Linux#75]
This is a feature request, not a bug.

What do you think about automatically mute or lower the sound during the ads when using the free version? Is it "too much"?

Regards, Iván.

**Comment by Ads20000** [comment]
Sounds to me like we shouldn't antagonise Spotify too much by muting or lowering the sound for ads, I imagine they would work harder to shut down Spotify Web if we did that (I did read something about them trying to wind down Spotify Web just for that reason, because people are already blocking the ads with adblockers and people can't (easily) do that with the desktop client)

**Comment by ilopmar** [comment]
Ok, that's what I thought but I wanted to now your oppinion.

Thanks!

**Comment by Ads20000** [comment]
Well ultimately it's up to @Quacky2200 but that's just my tuppence :)

**Comment by Quacky2200** [comment]
Whilst I hate the advertisements as much as everyone, I have to agree with Adam since they're always trying to push their application. I think their web player was something they thought was fun in 2012-ish, now they realised they can't remove it without disturbing a lot of users (esp. work restricted PC users) since they have more control over what happens on the application. As Adam said, they may try to push users away and remove the service in the future to prevent people blocking advertisements, who knows.

**Comment by ilopmar** [comment]
Thanks @Quacky2200. Keep your good work because this application is fantastic!
