### ISSUE TITLE
Accented characters show broken

### ISSUE THREAD

**Issue by Mondane** [Quacky2200/Spotify-Web-Player-for-Linux#77]
![image](https://cloud.githubusercontent.com/assets/1150272/23452176/9d65a206-fe63-11e6-8f49-7a54514921f6.png)

The album: https://play.spotify.com/album/7CEcf80Xiz9tyojLS9ZUp3

I see this happening with more accented characters on v1.0.40

**Comment by Quacky2200** [comment]
I am using the default install and I get this result: 

![special characters appear to work](https://cloud.githubusercontent.com/assets/4623599/23454858/8e2b88c6-fe65-11e6-9133-9c6285ce1ea1.png)

I have a feeling it could be something that either Spotify have gotten wrong (are you using another language on your account?), or perhaps you have a different default locale set up on your computer? UTF-8 should preferably be used with both

![locale under terminal](https://cloud.githubusercontent.com/assets/4623599/23454890/b0e237de-fe65-11e6-8465-d4e11d3b8653.png)

**Comment by Mondane** [comment]
It's only displayed incorrectly in the browse overview, other pages show the correct characters.

My locale:

```
locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
```

**Comment by Quacky2200** [comment]
That would probably be because Spotify release different pages/sections of the player into 'apps' (stupid name for it really) where it connects separately than other places of the site and places them into iframes. It's more than likely that since the apps are self-contained the bug hasn't been corrected within one of these 'apps' (discover/overview). Since you can recreate this issue, it would be best if you were to ask them on their [community forum](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/bd-p/001) that that this bug exists and that they need to correct it.

**Comment by Mondane** [comment]
Issue can indeed be closed, opening https://play.spotify.com/discover in Google Chrome or firefox shows the same contents.
