### ISSUE TITLE
Empty placeholders show on 'browse > new releases'

### ISSUE THREAD

**Issue by Mondane** [Quacky2200/Spotify-Web-Player-for-Linux#78]
See 

![image](https://cloud.githubusercontent.com/assets/1150272/23468029/fb595d6c-fe9f-11e6-9a19-279be7b1bf6f.png)

After opening such a placeholder, an black page is shown. Clicking on browse again, shows 

```
Not Found

The requested URL /apps/browse/7.1.6/ was not found on this server.
```

**Comment by Quacky2200** [comment]
This is an issue with Spotify, I do not directly request any URLs in the application to present music. 

It could be that they were changing something live or it could be that a script or page is cached after Spotify changed it. Closing the application and emptying your cache found in `~/.spotifywebplayer/` except `preferences.json`, `AlbumCache/`, and `LyricCache/` (**you will have to login again**) would be a good place to start. Otherwise, I would ask Spotify directly in their [community forum](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/bd-p/001).

**Comment by Mondane** [comment]
Issue can indeed be closed, opening https://play.spotify.com/discover in Google Chrome or firefox shows the same contents.
