### ISSUE TITLE
Played songs stay active on the notification icon

### ISSUE THREAD

**Issue by ilopmar** [Quacky2200/Spotify-Web-Player-for-Linux#8]
Every time a new song is played a notification is displayed. The problem is that after 30 minutes or so there are a lot of notifications on the icon and it's easy to miss a really important notification.

Maybe if there's a way to not "queue" the notification or make it not permanent or transient in some way, that would be great because after some seconds the notification will disappear.

**Comment by Quacky2200** [comment]
What distro are you using? 

In Ubuntu, there isn't a notification bell/icon so the notifications are dismissed afterwards rather than staying in a notification 'inbox'. For now, you can always turn off notifications. One idea is to only show playback differences rather than each new song?

**Comment by ilopmar** [comment]
I'm using Linux Mint 18 with Cinnamon as desktop manager.

![notifications](https://cloud.githubusercontent.com/assets/559192/18056820/c2cbe6fe-6e0d-11e6-92cd-5997c288fad7.png)

**Comment by Quacky2200** [comment]
Yeah, I can see how annoying that can be... I will definitely add it in the next version then. There won't be one for a couple of days to a week though.

**Comment by ilopmar** [comment]
Thanks! I've started using it today the application and I thinks it's great!

**Comment by JasonLG1979** [comment]
I could be very stupidly wrong(as I know nothing about electron)  but it looks like you're creating a new notification instance every time you change songs. I'm not 100% sure how libnotify works with your bindings but in the pyGObject(python) libnotify bindings the new method creates a new instance. (Again in python, but it might translate to you bindings) To make notifications replace each other you'd initialize notifications and retain a reference to a single notification instance. You'd then call update and show. Libnotify is kinda crusty though. You'd be better off just using dbus directly to interact with notifications. There's not really much to it.

**Comment by Quacky2200** [comment]
That's fine it's good to hear from someone who may know something in a different language. As far as I have been 'experimenting', dbus has been extremely difficult to add into as the libnode.so binding Electron uses is not the same as what the Node binary uses (either some kind of openssl implementation or something - I cannot debug that far though). 

I have had some success but it's been a slow process - currently I'm not trying to use D-Bus for notifications yet and only for MPRIS so that I can get keyboard controls and the sound menu working. I got it working but the implementation was unstable. Something I'm not prepared to sync to GitHub for.

Notifications are initialized on each song change (the way Electron works as far as I've seen),  It seems I would just have to use D-Bus if I wanted to change the actual notification instead of a new one then? How would I go about to show the same one - this is a bit confusing.

Also if you know much about dbus that you could perhaps guide me on this issue, it would be great :)
https://github.com/sidorares/node-dbus/issues/121 - that would mean I could use dbus-native instead of mpris-service.

**Comment by JasonLG1979** [comment]
I don't mean that dbus is easy or that mpris is easy either what I mean is that there's not much to the notifications interface. Dbus and especially mpris can be a PITA. But basically once you do manage to get the interface notifications return an id you would use that id to tell it to replace your old notification with a new one in place. That way you'd only ever have one notification because each notification would replace the previous one.

**Comment by JasonLG1979** [comment]
Here is an example I wrote for notifications that does NOT depend on libNotify for pyGObject. I'm not sure how helpful it will be. https://github.com/JasonLG1979/possibly-useful-scraps/wiki/SimpleDBusNotifications

**Comment by Quacky2200** [comment]
I will look into implementing the dbus notifications then :)

**Comment by JasonLG1979** [comment]
Oh, another thing. If you do decide implement notifications with dbus. And if you decide to do actions buttons(you may not? Unity doesn't support action buttons in notifications) or otherwise connect/bind/listen to(or whatever you call it?) the signals emitted by the notification interface you'll need to use that id returned by the notification to filter out all the noise from notifications that aren't yours. Otherwise you'll get signals about EVERY notification in the session.

Like this:
https://github.com/JasonLG1979/possibly-useful-scraps/blob/master/SimpleDBusNotifications.py#L116-L122

**Comment by Quacky2200** [comment]
Okay I have implemented the freedesktop-notifications library and these notifications do not support http images so they have to be cached first - adding that tiny bit extra time till it displays... :S. I will be uploading the new code soon but have to implement a few other things first before everything can be put up. It's looking good...

Oh I don't know if you're having problems with Spotify, but I cannot load any of my playlists which seems to be worrying... :S

**Comment by JasonLG1979** [comment]
> do not support http images so they have to be cached first

They are shown in the UI are they not already cached somewhere?

**Comment by JasonLG1979** [comment]
Browsers cache images to disk. I assumed electron would do the same.

**Comment by Quacky2200** [comment]
They do cache in the browser but I'm not prepared to go finding them right now o.0 haha

**Comment by Quacky2200** [comment]
Unless you were to be able to know which one these are assigned to without some kind of manifest - which I think is a bit too much work - you may as well just cache for the notification and then delete it on the next one.
![screenshot from 2016-09-03 12-45-19](https://cloud.githubusercontent.com/assets/4623599/18224629/6f868768-71d4-11e6-84eb-e331fef09266.png)

**Comment by JasonLG1979** [comment]
> you may as well just cache for the notification and then delete it on the next one

Probably. But you don't need to worry about deleting it if you put them in /tmp. It's up to the OS to do the house keeping in /tmp. But really if you wanted to use the cache it looks like it's incrementing  the file name. You wouldn't need to keep a manifest.

**Comment by Quacky2200** [comment]
The issue with that is knowing if the index is the same as the image in case of cache cleared, program exited etc etc, I think it's easier this way. That is true that the OS will wipe it but after listening to around 100 songs you may have 100 album covers you don't really need stored until a reboot - basically covering your backside in case anything *may* happen. :)

**Comment by JasonLG1979** [comment]
Can you not set your tmp template in electron. Meaning can you decide where the files are saved and a convention.

###pseudo code###
```
tmp_template = '/tmp/spotify_cover_cache/album_art_X'
song_index+= 1
current_album_art = tmp_template + song_index
```  

> basically covering your backside in case anything may happen. :)

100 album cover is not very much space and is a better option than deleting them after each use. You got to think about disc thrashing...

**Comment by Quacky2200** [comment]
Well at the moment the convention is just spotifyplayer-{trackuri} (without an extension) in /tmp, I can make a setting for the folder if you wish?

**Comment by JasonLG1979** [comment]
You don't need to have an option. What I mean by tmp template is that so you have a way to get/set a unique incrementable file name scheme.
```
tmp_template = '/tmp/spotify_cover_cache/album_art_X'
song_index+= 1
current_album_art = tmp_template + song_index
print(current_album_art)
>>> '/tmp/spotify_cover_cache/album_art_StuffUniqueToThisSession1'
```
File extensions don't matter for notification(or more generally for Linux at all really,lol)

**Comment by Quacky2200** [comment]
Yeah I've changed it to album names, it's consistent and that should remove more of the disk/network thrashing :)

**Comment by JasonLG1979** [comment]
DIY tmp template in python(with no error handling,lol):
```python
import os
import random
import string

Class TmpTemplate:
    def __init__(self):
        self._file_index = 0
        self._setup_template()

    def _setup_template(self):
        chars = string.ascii_uppercase, string.ascii_lowercase, string.digits
        filler_unique_to_session = ''.join(random.choice(chars) for i in range(48))
        tmp_location = '/tmp/spotify_cover_cache'
        if not os.path.isdir(tmp_location):
            os.makedirs(tmp_location)
        self._template = '{}/{}'.format(tmp_location, filler_unique_to_session)

    def write(self, stuff_you_want_to_save):
        self._file_index += 1
        unique_incremented_file_name = '{}{}'.format(self._template, self._file_index)
        with open(unique_incremented_file_name, 'w') as file:
            file.write(stuff_you_want_to_save)
        return self._file_index

    def read(self, index_of_file_you_want_to_read):
        unique_incremented_file_name = '{}{}'.format(self.template, index_of_file_you_want_to_read)
        with open(unique_incremented_file_name, 'r') as file:
            my_data = file.read()
        return my_data
```

**Comment by Quacky2200** [comment]
The should be fixed and notifications should share the same notification instance
