### ISSUE TITLE
Cannot log in anymore

### ISSUE THREAD

**Issue by orschiro** [Quacky2200/Spotify-Web-Player-for-Linux#85]
Dear @Quacky2200,

Do you have any idea how I can solve this problem?

![spotify login](https://cloud.githubusercontent.com/assets/170947/24551198/ebf9d5d8-1621-11e7-9677-37b290b090e9.gif)

**Comment by Quacky2200** [comment]
Please see this [temporary fix](https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/issues/67#issuecomment-285339768)

**Comment by orschiro** [comment]
Thank you!

If I understand correctly, then the fix involves changes the program code, correct?

Well, nevermind then. I will wait until the problem can be fixed without a temporary fix. :-)

**Comment by orschiro** [comment]
Thank you!

Does that mean that this software is going to be further developed despite the previous announcement to discontinue it?

**Comment by Quacky2200** [comment]
Sadly not, it was just something I had done mid-week and thought it'd be good for anyone who might want to use it. 

Personally, I don't think Spotify have the intent to allow everyone to play music everywhere (browsers and other players) since most people will use their app which they will continue to privatise. It was much better when they had their libspotify library to embed into music apps but they have basically deprecated the whole library in favour of a limited API and the need of an API key. Their reason for not releasing another up-to-date library is because they only think of the 2-5% which try to rip their music, whereas the others who want to use their service; continue to get disadvantaged.

**Comment by orschiro** [comment]
What a sad development. :-(
